name: Publish to NPM
on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          scope: '@saramorillon'

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Build sources
        run: pnpm build

      - name: Run tests
        run: pnpm vitest run

      - name: Publish package
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  send_discord_notification:
    runs-on: ubuntu-latest

    needs: build

    if: always()

    steps:
      - name: Send Discord notification
        shell: bash
        run: |
          result="${{ needs.build.result }}"
          repo_url="[${{ github.repository }}@${{ github.ref_name }}](<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}>)"
          curl -X POST -d "{\"content\":\"Publish $repo_url: **${result^^}**\"}" -H "Content-Type: application/json" ${{ secrets.DISCORD_WEBHOOK }}
